sudo: required
dist: trusty
language: python
python:
  - "3.5"
before_install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.2 postgresql-9.5-postgis-2.2-scripts


# database creation
before_script:
  - psql -c "create database travis_postgis;" -U postgres
  - ls /usr/share/postgresql/9.2/extension/
  - psql -c "CREATE EXTENSION postgis ;" -U postgres -d travis_postgis
  - psql -c "CREATE EXTENSION postgis_topology " -U postgres -d travis_postgis


install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov -U
  - pip install pytest-cov -U
  - pip install pytest-xdist -U
  - export PATH=/usr/lib/postgresql/9.4/bin:$PATH

# command to run tests using py.test

script:
#  - raster2pgsql
  - which raster2pgsql
  - retriever ls
  - retriever install postgres --database travis_postgis bioclim


after_success:
  - codecov

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=