sudo: false
language: python

matrix:
  include:
    - os: linux
      python: "3.5"

    - os: linux
      python: "2.7"

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.3.6
      before_install:
        - brew tap homebrew/php
        - brew update
        - mysql.server start
        - brew services start postgresql

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.12
      before_install:
        - brew tap homebrew/php
        - brew update
        - mysql.server start
        - brew services start postgresql

addons:
  postgresql: "9.4"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

services:
  - postgresql
  - mysql
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov -U
  - pip install pytest-cov -U
  - pip install pytest-xdist -U


# command to run tests using py.test

script:
  - py.test -v --cov=retriever

# database setup
before_script:
  - sqlite3 --version
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database testdb;' -U postgres

after_success:
  - codecov

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=
