cache: packages
sudo: required
warnings_are_errors: false

language: python
python:
  - "3.5"
services:
  - docker

# database setup
before_install:
-  docker-compose ps

install:
  - pip install codecov -U
  - pip install pytest-cov -U
  - pip install pytest-xdist -U
  # Use pytest 3.9.3 version since 3.10.0 has a bug
  - pip install pytest==3.9.3 -U

script:
-  docker-compose  run --service-ports python_retriever pytest -v --cov=retriever

after_success:
  - codecov
  - docker-compose -f down

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=
