sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
addons:
  postgresql: "10"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
      - gdal-bin
      - python-gdal
      - postgresql-10
      - postgresql-client-10
      # Development files and headers for GDAL
      - libgdal-dev
      - libgdal1-dev

services:
  - postgresql

env:
  global:
    - PGPORT=5433
    - SPRING_DATASOURCE_DATABASE=testdb
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=Password12!
    - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:${PGPORT}/${SPRING_DATASOURCE_DATABASE}
before_script:
#  - psql -c "CREATE USER ${SPRING_DATASOURCE_USERNAME} PASSWORD '${SPRING_DATASOURCE_PASSWORD}';"
  - psql -c "CREATE DATABASE ${SPRING_DATASOURCE_DATABASE} WITH OWNER = ${SPRING_DATASOURCE_USERNAME};"

  - psql -c 'CREATE EXTENSION postgis WITH  SCHEMA testdb;'  -U postgres
  - psql -c 'CREATE EXTENSION postgis_topology WITH SCHEMA  testdb;'  -U postgres
## - psql -c "ALTER USER travis WITH PASSWORD 'Password12!';" -U postgres
#  - psql -c 'create database testdb;' -U postgres
#  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d testdb
#  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d testdb

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov -U
  - pip install pytest-cov -U
  - pip install pytest-xdist -U


# command to run tests using py.test

script:
  - raster2pgsql
  - which raster2pgsql

# database setup
#before_script:
#  - sqlite3 --version
##  - psql -c "ALTER USER travis WITH PASSWORD 'Password12!';" -U postgres
#  - psql -c 'create database testdb;' -U postgres
#  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d testdb
#  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d testdb

after_success:
  - codecov

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=
