language: python
sudo: required
dist: precise
addons:
    postgresql: "9.5"
services:
    - postgresql
matrix:
  include:
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.3.6
      osx_image: xcode8.3
      before_install:
        - brew install mariadb
        - mysql.server start
        # - brew services start postgresql
      
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.12
      osx_image: xcode8.3
      before_install:
        - brew install mysql
        - mysql.server start
        # - brew services start postgresql

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov -U
  - pip install pytest-cov -U
  - pip install pytest-xdist -U


# command to run tests using py.test

script:
  - py.test -v --cov=retriever

# database setup
before_script:
  - sqlite3 --version
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'billy'@'localhost' IDENTIFIED BY 'supersecret';" -uroot
  - mysql -e "create database sqlectron;" -uroot
  - mysql -e "CREATE USER 'travis'@'localhost';GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost';GRANT FILE ON *.* TO 'travis'@'localhost';" -uroot
  # - printf "[client]\nusername=travis\npassword=supersecret\n" > ~/.my.cnf
# # postgres

# before_script:
#   # - psql -c "CREATE DATABASE testing_db;" -U postgres
#   # - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
#   # - printf ("[rs-dbi]\nusername=billy\npassword=supersecret\n") > ~/.my.cnf
#   # - printf "localhost:*:testdb:postgres:Password12!" > ~/.my.cnf

  - psql -c "CREATE USER postgres WITH PASSWORD 'Password12!'" -U postgres
  - psql -c 'CREATE DATABASE testdb' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE testdb to postgres'
  - printf "localhost:*:testdb:postgres:Password12!" > ~/.pgpass

after_success:
  - codecov

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=
