sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
addons:
  postgresql: "9.4"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
      - gdal-bin
      - python-gdal
      - postgresql-10
      - postgresql-client-10
      - postgresql-9.4-postgis-2.3
      # Development files and headers for GDAL
      - libgdal-dev
      - libgdal1-dev
      - libgeos-dev
      - libproj-dev
      - tree

services:
  - postgresql
#
#env:
#  global:
#    - PGPORT=5433
#    - SPRING_DATASOURCE_DATABASE=testdb
#    - SPRING_DATASOURCE_USERNAME=postgres
##    - SPRING_DATASOURCE_PASSWORD=Password12!
#    - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:${PGPORT}/${SPRING_DATASOURCE_DATABASE}
before_script:
#
#psql -c "CREATE USER postgres WITH PASSWORD 'Password12!'"
#psql -c 'CREATE DATABASE testdb'
#psql -c 'GRANT ALL PRIVILEGES ON DATABASE testdb to postgres'
#​
#Create .pgpass in your home directory:
#localhost:*:testdb:postgres:Password12!
#  - psql -c "CREATE USER ${SPRING_DATASOURCE_USERNAME} PASSWORD '${SPRING_DATASOURCE_PASSWORD}';"
#  - psql -c 'create database testdb;' -U postgres
##  - psql -c "ALTER USER CURRENT_USER WITH PASSWORD 'Password12!'" -U postgres;
##  - psql -c 'CREATE EXTENSION postgis WITH  SCHEMA testdb;'  -U postgres
#  - psql -d testdb -c 'CREATE EXTENSION postgis;' -U postgres
  - psql -U postgres -c "create database testdb"
  - psql -U postgres -d testdb -c "create extension postgis"
  - psql -U postgres -d testdb -c "create extension postgis_topology"
#  - psql -c "CREATE USER postgres WITH PASSWORD 'Password12!'"

#  - psql -c 'CREATE DATABASE testdb'
#  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE testdb to postgres

#  - psql -c 'CREATE EXTENSION postgis_topology WITH SCHEMA  testdb;'  -U postgres

#  - psql -c "create user rtester with createdb login password 'rtester'" -U postgres
#- psql -c "create database pybossa_test owner rtester encoding 'UTF-8' lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8' template template0;" -U postgres
## - psql -c "ALTER USER travis WITH PASSWORD 'Password12!';" -U postgres
#  - psql -c 'create database testdb;' -U postgres
#  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d testdb
#  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d testdb

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov -U
  - pip install pytest-cov -U
  - pip install pytest-xdist -U
  - export PATH=/usr/lib/postgresql/9.4/bin:$PATH

# command to run tests using py.test

script:
#  - raster2pgsql
#  - which raster2pgsql
#  - ls /usr/lib/postgresql/9.4/bin
  - tree /usr/lib/postgresql
  - tree usr/local/postgis/
  - tree /usr/local/bin/
# database setup
#before_script:
#  - sqlite3 --version
##  - psql -c "ALTER USER travis WITH PASSWORD 'Password12!';" -U postgres
#  - psql -c 'create database testdb;' -U postgres
#  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d testdb
#  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d testdb

after_success:
  - codecov

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=
